bishe/blueprints/function.py
# -*- coding: utf-8 -*-

from flask import render_template, flash, redirect, url_for, \
    Blueprint, session, current_app, send_from_directory, request, Response
from flask_login import login_required, current_user
from bishe.forms import ApplyForm
from bishe.models import Apply, Student, Academic, Pass, School, Revoke
from bishe.extensions import db, bloomfilter
from bishe.utils import random_filename, redirect_back, getNewAddress, transaction, getInformation, cmp_json
from datetime import datetime
import os
import json

func_bp = Blueprint('function', __name__)


@func_bp.route('/apply', methods=['GET', 'POST'])
@login_required
def apply():
    form = ApplyForm()
    if form.validate_on_submit():
        name = session['message']['name']
        school = form.school.data
        department = form.department.data
        major = form.major.data
        in_time = form.in_time.data
        out_time = form.out_time.data
        _type = form.type.data
        level = form.level.data
        year = form.year.data

        f = form.image.data
        filename = random_filename(f.filename)

        my_apply = Apply.query.filter_by(
            name=name,
            school=school,
            department=department,
            major=major,
            type=_type,
            level=level,
            year=year
        ).first()

        if my_apply and my_apply.apply_statue != 0:
            flash("待审核或已通过，请勿重复申请", "warning")
        else:
            my_apply = Apply(
                name=name,
                school=school,
                department=department,
                major=major,
                in_time=in_time,
                out_time=out_time,
                type=_type,
                level=level,
                year=year,
                apply_statue=2,
                image=filename,
                student=Student.query.get(current_user.seed)
            )

            db.session.add(my_apply)
            db.session.commit()

            f.save(os.path.join(current_app.config['IMAGE_SAVE_PATH'], filename))

            flash("申请成功,请等待审核", "info")
            return redirect(url_for('function.profile_apply', apply_id=my_apply.id))

    return render_template('function/apply.html', form=form, message=session['message'])


# 申请表信息
@func_bp.route('/profile_apply/<int:apply_id>')
@login_required
def profile_apply(apply_id):
    apply_table = Apply.query.get(apply_id)
    if current_user.role == '2':
        return render_template('function/check_apply.html', apply_table=apply_table)

    return render_template('function/profile_apply.html', apply_table=apply_table)


# 证书信息
@func_bp.route('/profile_academic/<string:hash_value>')
def profile_academic(hash_value):
    academic = Academic.query.get(hash_value)
    try:
        jsonData = getInformation(hash_value)
        academic_json = academic.to_json()

        believable = cmp_json(academic_json, jsonData)
    except:
        believable = False

    if current_user.is_authenticated and current_user.role == '2':
        return render_template('function/check_academic.html', academic=academic, believable=believable)

    return render_template('function/profile_academics.html', academic=academic, believable=believable)


@func_bp.route('/pass_confirm/<int:apply_id>', methods=['POST'])  # apply_table有属性未添加
@login_required
def pass_confirm(apply_id):
    if request.json:
        quest = request.json

    apply_table = Apply.query.get(apply_id)
    school = School.query.get(current_user.seed)

    student_seed = apply_table.student.seed
    current_add = getNewAddress(current_user.seed)
    print(current_add)
    pass_time = datetime.now()

    form = {
        "name": apply_table.name,
        "school": apply_table.school,
        "department": apply_table.department,
        "major": apply_table.major,
        "in_time": apply_table.in_time.strftime('%Y-%m-%d'),
        "out_time": apply_table.out_time.strftime('%Y-%m-%d'),
        "type": apply_table.type,
        "level": apply_table.level,
        "year": apply_table.year,
        "pass_time": pass_time.strftime('%Y-%m-%d'),
        "image": apply_table.image,
        "student_seed": student_seed,
        "dealer_seed": current_user.seed
    }

    hash_value = transaction(student_seed, current_add, form)
    print(hash_value)
    # hash_value = getNewSeed()
    remark = '于' + pass_time.strftime('%Y-%m-%d %H:%M:%S') + '由' + school.name + '确认通过<br>'

    pass_table = Pass(
        school=apply_table.school,
        pass_time=pass_time,
        dealer=school
    )

    academic = Academic(
        hash_value=hash_value,
        name=apply_table.name,
        school=apply_table.school,
        department=apply_table.department,
        major=apply_table.major,
        in_time=apply_table.in_time,
        out_time=apply_table.out_time,
        type=apply_table.type,
        level=apply_table.level,
        year=apply_table.year,
        status=1,
        image=apply_table.image,
        pass_time=pass_time,
        remark=remark,
        student=apply_table.student,
        pass_table=pass_table,
        dealer_seed=current_user.seed
    )

    db.session.add(pass_table)
    db.session.add(academic)

    apply_table.apply_statue = 1
    apply_table.dealer = school
    apply_table.deal_time = pass_time
    apply_table.remark = remark
    apply_table.hash_value = hash_value

    db.session.commit()

    bloomfilter.add(hash_value)

    flash('通过成功', 'success')
    return Response(json.dumps({'success': True}), mimetype='application/json')


@func_bp.route('/unpass_confirm/<int:apply_id>', methods=['POST'])
@login_required
def unpass_confirm(apply_id):
    if request.json is None:
        return Response(json.dumps({'success': False}), mimetype='application/json')

    quest = request.json
    try:
        reason = quest['reason']
    except:
        reason = ''

    if reason == '':
        reason = '未通过原因：无'
    else:
        reason = '未通过原因：' + reason

    unpass_time = datetime.now()
    reason = '于' + unpass_time.strftime('%Y-%m-%d %H:%M:%S') + '由' + session['message']['name'] + '不予通过<br>' + reason

    apply_table = Apply.query.get(apply_id)
    apply_table.apply_statue = 0
    apply_table.dealer = School.query.get(current_user.seed)
    apply_table.deal_time = unpass_time
    apply_table.remark = reason
    db.session.commit()

    flash('已确认该申请不通过', 'info')
    return Response(json.dumps({'success': True}), mimetype='application/json')


@func_bp.route('/revoke_confirm/<string:hash_value>', methods=['POST'])
@login_required
def revoke_confirm(hash_value):
    if request.json is None:
        return Response(json.dumps({'success': False}), mimetype='application/json')

    quest = request.json
    try:
        reason = quest['reason']
    except:
        reason = ''

    if reason == '':
        reason = '撤销原因：无<br>'
    else:
        reason = '撤销原因：' + reason + '<br>'

    revoke_time = datetime.now()
    reason = '于' + revoke_time.strftime('%Y-%m-%d %H:%M:%S') + '由' + session['message']['name'] + '撤销<br>' + reason

    academic = Academic.query.get(hash_value)
    academic.status = 0
    if academic.remark:
        academic.remark = academic.remark + reason
    else:
        academic.remark = reason

    revoke_table = Revoke(
        school=academic.school,
        revoke_time=revoke_time,
        reason=reason,
        dealer=School.query.get(current_user.seed),
        academic=academic
    )

    db.session.add(revoke_table)
    db.session.commit()

    flash('已撤销该证书', 'info')
    return Response(json.dumps({'success': True}), mimetype='application/json')


@func_bp.route('/recover_confirm/<string:hash_value>', methods=['POST'])
@login_required
def recover_confirm(hash_value):
    if request.json is None:
        return Response(json.dumps({'success': False}), mimetype='application/json')

    quest = request.json
    try:
        reason = quest['reason']
    except:
        reason = ''

    if reason == '':
        reason = '恢复原因：无<br>'
    else:
        reason = '恢复原因：' + reason + '<br>'

    recover_time = datetime.now()
    reason = '于' + recover_time.strftime('%Y-%m-%d %H:%M:%S') + '由' + session['message']['name'] + '恢复<br>' + reason

    academic = Academic.query.get(hash_value)
    academic.status = 1
    academic.remark = academic.remark + reason
    revoke_table = academic.revoke_table
    db.session.delete(revoke_table)
    db.session.commit()

    flash('已恢复该证书', 'info')
    return Response(json.dumps({'success': True}), mimetype='application/json')


# 获取图片
@func_bp.route('/get_image/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['IMAGE_SAVE_PATH'], filename)


@func_bp.route('/avatars/<path:filename>')
@login_required
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


# 搜索
@func_bp.route('/search')
def search():
    q = request.args.get('q', '').strip()
    if q == '':
        flash('请输入要查询的证书hash值/姓名/学校/学院/专业.', 'warning')
        return redirect_back()

    if len(q) == 81:
        if q in bloomfilter:
            return redirect(url_for('function.profile_academic', hash_value=q))
        else:
            if current_user.is_authenticated and current_user.role == '2':
                return render_template('function/check_academic.html', academic=None)
            return render_template('function/profile_academics.html', academic=None)

    category = request.args.get('category', 'academic')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_SEARCH_RESULT_PER_PAGE']

    if category == 'apply' and current_user.is_authenticated and current_user.role == '2':
        pagination = Apply.query.filter_by(
            school=session['message']['organization']).whooshee_search(q).paginate(page, per_page)
    else:
        pagination = Academic.query.whooshee_search(q).paginate(page, per_page)

    results = pagination.items

bishe/blueprints/users.py
# -*- coding: utf-8 -*-

from flask import render_template, flash, Blueprint, session, \
    request, Response, redirect, url_for, current_app
from flask_login import login_required, current_user, logout_user
from bishe.models import User_auth, Student, Apply, Academic, School, Pass, Revoke
import json
import traceback

from bishe.extensions import db

users_bp = Blueprint('users', __name__)


@users_bp.route('/cv', methods=['GET', 'POST'])
@login_required
def cv():
    if current_user.role == "1":  # Student
        user = Student.query.get(current_user.seed)
        academics = user.academics
        apply_tables = user.apply_table
        return render_template('users/cv.html', message=session['message'], academics=academics,
                               apply_tables=apply_tables)
    elif current_user.role == "2":  # School
        user = School.query.get(current_user.seed)
        apply_tables = user.apply_table
        pass_academics = Academic.query.filter_by(dealer_seed=current_user.seed, status=1).all()
        revoke_tables = user.revoke_table
        return render_template('users/cv.html', message=session['message'], apply_tables=apply_tables,
                               pass_academics=pass_academics, revoke_tables=revoke_tables)
    else:
        return render_template('users/cv.html', message=session['message'])


@users_bp.route('/myapply')
@login_required
def myapply():
    if current_user.role != "1":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Apply.query.filter_by(student_seed=current_user.seed).paginate(page, per_page)
    apply_tables = pagination.items
    return render_template('users/apply_tables.html', apply_tables=apply_tables,
                           title='我的申请表', pagination=pagination)


@users_bp.route('/myacademic')
@login_required
def myacademic():
    if current_user.role != "1":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Academic.query.filter_by(student_seed=current_user.seed).paginate(page, per_page)
    academics = pagination.items
    return render_template('users/academics.html', academics=academics,
                           title='我的证书', pagination=pagination)


@users_bp.route('/wait_deal')
@login_required
def wait_deal():
    if current_user.role != "2":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Apply.query.filter_by(school=session['message']['organization'],
                                         apply_statue=2).order_by("apply_time").paginate(page, per_page)
    apply_tables = pagination.items
    return render_template('users/apply_tables.html', apply_tables=apply_tables,
                           title='待处理申请表', isnone='暂未有待处理申请表信息', pagination=pagination)


@users_bp.route('/have_deal')
@login_required
def have_deal():
    if current_user.role != "2":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Apply.query.filter(
                    Apply.school == session['message']['organization']
                ).filter(
                    db.or_(Apply.apply_statue == 0, Apply.apply_statue == 1)
                ).order_by("apply_time").paginate(page, per_page)
    apply_tables = pagination.items
    return render_template('users/apply_tables.html', apply_tables=apply_tables,
                           title='已处理申请表', isnone='暂未有已处理申请表信息', pagination=pagination)


@users_bp.route('/pass_academics')
@login_required
def pass_academics():
    if current_user.role != "2":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Academic.query.filter_by(school=session['message']['organization'],
                                          status=1).paginate(page, per_page)
    academics = pagination.items
    return render_template('users/academics.html', academics=academics,
                           title='已允许通过的学历证书', isnone='暂未有允许通过的学历证书', pagination=pagination)


@users_bp.route('/revoke_academics')
@login_required
def revoke_academics():
    if current_user.role != "2":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Academic.query.filter_by(school=session['message']['organization'],
                                          status=0).paginate(page, per_page)
    academics = pagination.items
    return render_template('users/academics.html', academics=academics,
                           title='撤销的学历证书', isnone='暂未有撤销的学历证书', pagination=pagination)


@users_bp.route('/update', methods=['POST'])
@login_required
def update():
    if request.json is None:
        return Response(json.dumps({'success': False, 'message': '参数错误，请检查客户端版本', 'code': 1}),
                        mimetype='application/json')
    quest = request.json
    try:
        try:
            phone = quest['phone']
        except:
            phone = ''
        try:
            email = quest['email']
        except:
            email = ''
        try:
            passwd = quest['password']
        except:
            passwd = ''

        if phone != '':
            if User_auth.query.filter_by(phone=phone).first():
                return Response(json.dumps({'success': False, 'message': '电话号码已被占用', 'code': 3}),
                                mimetype='application/json')
            current_user.phone = phone
        if email != '':
            if User_auth.query.filter_by(email=email).first():
                return Response(json.dumps({'success': False, 'message': '邮箱已被占用', 'code': 3}),
                                mimetype='application/json')
            current_user.email = email
        if passwd != '':
            if len(passwd) < 10:
                return Response(json.dumps({'success': False, 'message': '密码过短', 'code': 4}),
                                mimetype='application/json')
            current_user.set_password(passwd)

        db.session.commit()

        if passwd != '':
            flash("密码已修改，请重新登录", 'info')
            logout_user()
        else:
            flash("更新成功", "info")
        return Response(json.dumps({'success': True, 'message': '成功', 'code': 0}), mimetype='application/json')
    except BaseException as e:
        traceback.print_exc()
        print(e)
        return Response(json.dumps({'success': False, 'message': '服务器端发生错误', 'code': 1}), mimetype='application/json')

bishe/templates/function/index.html
{% extends 'base.html' %}

{% block title %} 功能主页 {% endblock %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/mdui.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/func_index.css') }}">
{% endblock %}

{% block main %}
    <main class="page projects-page">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}

        <section class="portfolio-block projects-cards">
            <div class="container">
                <div class="row">
                    {% if current_user.role == "1" %}
                        <div class="col-md-4 col-lg-4">
                            <div class="card border-0">
                                <a href="{{ url_for('function.apply') }}">
                                    <img src="{{ url_for('static', filename='img/apply.jpg') }}" alt="Card Image" class="card-img-top scale-on-hover">
                                </a>
                                <div class="card-body">
                                    <h6><a href="{{ url_for('function.apply') }}">申请学历</a></h6>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-lg-4">
                            <div class="card border-0">
                                <a mdui-dialog="{target: '#update-info-dialog'}">
                                    <img src="{{ url_for('static', filename='img/search.jpg') }}" alt="Card Image" class="card-img-top scale-on-hover">
                                </a>
                                <div class="card-body">
                                    <h6><a mdui-dialog="{target: '#update-info-dialog'}">查询学历</a></h6>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-lg-4">
                            <div class="card border-0">
                                <a href="{{ url_for('users.myapply') }}">
                                    <img src="{{ url_for('static', filename='img/apply_table.jpg') }}" alt="Card Image" class="card-img-top scale-on-hover">
                                </a>
                                <div class="card-body">
                                    <h6><a href="{{ url_for('users.myapply') }}">我的申请表</a></h6>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-lg-4">
                            <div class="card border-0">
                                <a href="{{ url_for('users.myacademic') }}">
                                    <img src="{{ url_for('static', filename='img/acadamic.jpg') }}" alt="Card Image" class="card-img-top scale-on-hover">
                                </a>
                                <div class="card-body">
                                    <h6><a href="{{ url_for('users.myacademic') }}">我的证书</a></h6>
                                </div>
                            </div>
                        </div>

                    {% elif current_user.role == "2" %}
                        <div class="col-md-5 col-lg-4">
                            <div class="card border-0">
                                <a href="{{ url_for('users.wait_deal') }}">
                                    <img src="{{ url_for('static', filename='img/wait_deal.jpg') }}" alt="Card Image" class="card-img-top scale-on-hover">
                                </a>
                                <div class="card-body">
                                    <h6><a href="{{ url_for('users.wait_deal') }}">待处理申请表</a></h6>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-5 col-lg-4">
                            <div class="card border-0">
                                <a href="{{ url_for('users.have_deal') }}">
                                    <img src="{{ url_for('static', filename='img/have_deal.jpg') }}" alt="Card Image" class="card-img-top scale-on-hover">
                                </a>
                                <div class="card-body">
                                    <h6><a href="{{ url_for('users.have_deal') }}">已处理申请表</a></h6>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-5 col-lg-4">
                            <div class="card border-0">
                                <a href="{{ url_for('users.pass_academics') }}">
                                    <img src="{{ url_for('static', filename='img/acadamic.jpg') }}" alt="Card Image" class="card-img-top scale-on-hover">
                                </a>
                                <div class="card-body">
                                    <h6><a href="{{ url_for('users.pass_academics') }}">允许通过的证书</a></h6>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-5 col-lg-4">
                            <div class="card border-0">
                                <a href="{{ url_for('users.revoke_academics') }}">
                                    <img src="{{ url_for('static', filename='img/revoke.jpg') }}" alt="Card Image" class="card-img-top scale-on-hover">
                                </a>
                                <div class="card-body">
                                    <h6><a href="{{ url_for('users.revoke_academics') }}">撤销的证书</a></h6>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-5 col-lg-4">
                            <div class="card border-0">
                                <a mdui-dialog="{target: '#update-info-dialog'}">
                                    <img src="{{ url_for('static', filename='img/search.jpg') }}" alt="Card Image" class="card-img-top scale-on-hover">
                                </a>
                                <div class="card-body">
                                    <h6><a mdui-dialog="{target: '#update-info-dialog'}">查询学历或申请表</a></h6>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </section>
    </main>

    <div class="mdui-dialog" id="update-info-dialog">
        <div class="mdui-dialog-content">
            <div class="mdui-appbar mdui-appbar-fixed">
                <div class="mdui-toolbar mdui-color-theme mdui-text-color-white">
                    <a mdui-dialog-close class="mdui-btn mdui-btn-icon">
                        <i class="mdui-icon material-icons">X</i>
                    </a>
                    <span class="mdui-typo-title">证书查询</span>
                </div>
            </div>
            <!-- 浮动标签 -->
            <form action="{{ url_for('function.search') }}">
                <p style="margin-top:60px">请输入81位证书Hash值/姓名/学校/学院/专业中的一个,支持组合查询</p>
                <div class="mdui-textfield mdui-textfield-floating-label">
                    <label class="mdui-textfield-label">证书Hash值/姓名/学校/学院/专业</label>
                    <input type="text" id="search_academic" name="q" class="mdui-textfield-input" required/>
                </div>

                <button class="mdui-btn mdui-btn-raised mdui-ripple mdui-color-theme-accent mdui-float-right" type="submit">
                    查询
                </button>
            </form>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='js/mdui.min.js') }}"></script>
    <script>
        function updateInfo(){

        }
    </script>
{% endblock %}

bishe/templates/function/profile_academics.html
{% extends 'base.html' %}

{% block title %}
    学历证书 - {{ academic.school }} - {{ academic.major }} - {{ academic.type }} - {{ academic.name }}
{% endblock %}

{% block style %}
    <style type="text/css">
		.portfolio-block {
			padding-bottom: 100px;
			padding-top: 100px;
		}

		td{
			width: 100px;
		}

        .three_button{
            padding-bottom: 10px;
        }
	</style>
{% endblock %}

{% block main %}
    <main class="page lanidng-page">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}

        <section class="portfolio-block block-intro">
            <div class="container">
                {% if academic %}
                    <div class="center-block three_button">
                        <input type='button' name='submit' onclick='javascript:history.back(-1);' value='返回上一页'>
                    </div>
                    <table border="1" width="800" height="800" align="center" cellspacing="0">
                        <tr align="center">
                            <td bgcolor="#ededed">姓名</td>
                            <td colspan="2">{{ academic.name }}</td>
                            <td bgcolor="#ededed">毕业院校</td>
                            <td colspan="2">{{ academic.school }}</td>
                            <td colspan="2" rowspan="3">
                                <img src="{{ url_for('function.get_image', filename=academic.image) }}"
                                    style="height: 20%; width: 100%">
                            </td>
                        </tr>
                        <tr align="center">
                            <td bgcolor="#ededed">学院名称</td>
                            <td colspan="2">{{ academic.department }}</td>
                            <td bgcolor="#ededed">专业名称</td>
                            <td colspan="2">{{ academic.major }}</td>
                        </tr>
                        <tr align="center">
                            <td bgcolor="#ededed">入学时间</td>
                            <td colspan="2">{{ academic.in_time }}</td>
                            <td bgcolor="#ededed">毕业时间</td>
                            <td colspan="2">{{ academic.out_time }}</td>
                        </tr>
                        <tr align="center">
                            <td bgcolor="#ededed">学历类型</td>
                            <td colspan="2">{{ academic.type }}</td>
                            <td bgcolor="#ededed">学历层次</td>
                            <td colspan="2">{{ academic.level }}</td>
                            <td bgcolor="#ededed">学制</td>
                            <td>{{ academic.year }}</td>
                        </tr>
                        <tr align="center">
                            <td bgcolor="#ededed">通过时间</td>
                            <td colspan="2">{{ academic.pass_time.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                            <td bgcolor="#ededed">处理人</td>
                            <td colspan="2">{{ academic.pass_table.dealer.name }}</td>
                            <td bgcolor="#ededed">毕结业结论</td>
                            {% if academic.status == 0 %}
                                <td colspan="1"><p style="color: red; font-size: 16px">已撤销</p></td>
                            {% elif academic.status == 1 %}
                                <td colspan="1">毕业</td>
                            {% endif %}
                        </tr>
                        <tr align="center">
                            <td bgcolor="#ededed">证书Hash值</td>
                            <td colspan="7" align="left">
                                <p style="word-break: break-all; font-size: 16px">{{ academic.hash_value }}</p>
                            </td>
                        </tr>
                        <tr align="center">
                            <td bgcolor="#ededed">证书信息校验</td>
                            {% if believable %}
                                <td colspan="7" align="left" style="color: #00b0ff">校验通过，证书信息可信</td>
                            {% else %}
                                <td colspan="7" align="left" style="color: red">校验失败，证书信息不可信</td>
                            {% endif %}
                        </tr>
                        <tr align="center">
                            <td bgcolor="#ededed" rowspan="2">备注</td>
                            <td colspan="7" rowspan="2" align="left" valign="top">
                                {% if academic.remark %}
                                    <p style="word-break: break-all; font-size: 16px">{{ academic.remark|safe }}</p>
                                {% endif %}
                            </td>
                        </tr>
                    </table>
                {% else %}
                    <a href="javascript:history.back(-1)">所查询的证书不存在，点击返回上一页</a>
                {% endif %}
            </div>
        </section>
    </main>
{% endblock %}