bishe/blueprints/auth.py
# -*- coding: utf-8 -*-

from flask import render_template, flash, redirect, url_for, Blueprint, session
from flask_login import login_user, logout_user, login_required, current_user
from flask_avatars import Identicon

from bishe.forms import LoginForm, RegisterForm
from bishe.models import User_auth, Student, School, Institution
from bishe.utils import judge_seed, judge_phone, judge_email, getNewSeed, random_avatar
from bishe.extensions import db

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('homepage.index'))

    form = LoginForm()
    if form.validate_on_submit():

        username = form.username.data
        password = form.password.data
        remember = form.remember.data

        if judge_seed(username):
            user = User_auth.query.filter_by(seed=username).first()
        elif judge_email(username):
            user = User_auth.query.filter_by(email=username).first()
        elif judge_phone(username):
            user = User_auth.query.filter_by(phone=username).first()
        else:
            flash('用户名不正确，需为81位Seed或邮箱或手机号', 'warning')
            return render_template('auth/login.html', form=form)

        if user:
            if user.validate_password(password):
                login_user(user, remember)

                if user.role == "1":
                    user_message = Student.query.get(user.seed)
                    message = {'name': user_message.name}
                    session['message'] = message
                elif user.role == "2":
                    user_message = School.query.get(user.seed)
                    message = {'name': user_message.name, 'organization': user_message.organization}
                    session['message'] = message
                elif user.role == "3":
                    user_message = Institution.query.get(user.seed)
                    message = {'name': user_message.name, 'organization': user_message.organization}
                    session['message'] = message

                return redirect(url_for('homepage.index'))
            flash('用户名或密码错误', 'warning')
        else:
            flash('用户名不存在', 'warning')

    return render_template('auth/login.html', form=form)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('homepage.index'))

    form = RegisterForm()

    if form.validate_on_submit():
        name = form.name.data
        phone = str(form.phone.data)
        email = form.email.data
        password = form.password.data
        role = form.role.data
        organization = form.organization.data


        check_email = User_auth.query.filter_by(email=email).first()
        if check_email:
            flash('该邮箱已被注册，请尝试直接登录', 'warning')
            return render_template('auth/register.html', form=form)

        check_phone = User_auth.query.filter_by(phone=phone).first()
        if check_phone:
            flash('该号码已被注册，请尝试直接登录', 'warning')
            return render_template('auth/register.html', form=form)

        if role != 0 and organization is None:
            flash('校名/机构名不能为空！', 'warning')
            return render_template('auth/register.html', form=form)

        seed = getNewSeed()
        avatar = Identicon()
        filenames = avatar.generate(text=random_avatar())[2]

        user_auth = User_auth(
            seed=seed,
            phone=phone,
            email=email,
            role=role,
            image=filenames
        )
        user_auth.set_password(password)
        db.session.add(user_auth)

        if role == "1":#Student
            user = Student(
                seed=seed,
                name=name
            )
            db.session.add(user)
        elif role == "2":#School
            user = School(
                seed=seed,
                name=name,
                organization=organization
            )
            db.session.add(user)
        elif role == "3":#Institution
            user = Institution(
                seed=seed,
                name=name,
                organization=organization
            )
            db.session.add(user)

        db.session.commit()

        message = '注册成功，你的Seed为：'+seed+'，请妥善保管'
        flash(message, 'info')
        return redirect(url_for('auth.login'))

    return render_template('auth/register.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return render_template('homepage/index.html')

bishe/blueprints/users.py
# -*- coding: utf-8 -*-

from flask import render_template, flash, Blueprint, session, \
    request, Response, redirect, url_for, current_app
from flask_login import login_required, current_user, logout_user
from bishe.models import User_auth, Student, Apply, Academic, School, Pass, Revoke
import json
import traceback

from bishe.extensions import db

users_bp = Blueprint('users', __name__)


@users_bp.route('/cv', methods=['GET', 'POST'])
@login_required
def cv():
    if current_user.role == "1":  # Student
        user = Student.query.get(current_user.seed)
        academics = user.academics
        apply_tables = user.apply_table
        return render_template('users/cv.html', message=session['message'], academics=academics,
                               apply_tables=apply_tables)
    elif current_user.role == "2":  # School
        user = School.query.get(current_user.seed)
        apply_tables = user.apply_table
        pass_academics = Academic.query.filter_by(dealer_seed=current_user.seed, status=1).all()
        revoke_tables = user.revoke_table
        return render_template('users/cv.html', message=session['message'], apply_tables=apply_tables,
                               pass_academics=pass_academics, revoke_tables=revoke_tables)
    else:
        return render_template('users/cv.html', message=session['message'])


@users_bp.route('/myapply')
@login_required
def myapply():
    if current_user.role != "1":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Apply.query.filter_by(student_seed=current_user.seed).paginate(page, per_page)
    apply_tables = pagination.items
    return render_template('users/apply_tables.html', apply_tables=apply_tables,
                           title='我的申请表', pagination=pagination)


@users_bp.route('/myacademic')
@login_required
def myacademic():
    if current_user.role != "1":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Academic.query.filter_by(student_seed=current_user.seed).paginate(page, per_page)
    academics = pagination.items
    return render_template('users/academics.html', academics=academics,
                           title='我的证书', pagination=pagination)


@users_bp.route('/wait_deal')
@login_required
def wait_deal():
    if current_user.role != "2":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Apply.query.filter_by(school=session['message']['organization'],
                                         apply_statue=2).order_by("apply_time").paginate(page, per_page)
    apply_tables = pagination.items
    return render_template('users/apply_tables.html', apply_tables=apply_tables,
                           title='待处理申请表', isnone='暂未有待处理申请表信息', pagination=pagination)


@users_bp.route('/have_deal')
@login_required
def have_deal():
    if current_user.role != "2":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Apply.query.filter(
                    Apply.school == session['message']['organization']
                ).filter(
                    db.or_(Apply.apply_statue == 0, Apply.apply_statue == 1)
                ).order_by("apply_time").paginate(page, per_page)
    apply_tables = pagination.items
    return render_template('users/apply_tables.html', apply_tables=apply_tables,
                           title='已处理申请表', isnone='暂未有已处理申请表信息', pagination=pagination)


@users_bp.route('/pass_academics')
@login_required
def pass_academics():
    if current_user.role != "2":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Academic.query.filter_by(school=session['message']['organization'],
                                          status=1).paginate(page, per_page)
    academics = pagination.items
    return render_template('users/academics.html', academics=academics,
                           title='已允许通过的学历证书', isnone='暂未有允许通过的学历证书', pagination=pagination)


@users_bp.route('/revoke_academics')
@login_required
def revoke_academics():
    if current_user.role != "2":
        flash("你无权访问该页面", "warning")
        redirect(url_for('homepage.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['IOTA_LIST_PER_PAGE']
    pagination = Academic.query.filter_by(school=session['message']['organization'],
                                          status=0).paginate(page, per_page)
    academics = pagination.items
    return render_template('users/academics.html', academics=academics,
                           title='撤销的学历证书', isnone='暂未有撤销的学历证书', pagination=pagination)


@users_bp.route('/update', methods=['POST'])
@login_required
def update():
    if request.json is None:
        return Response(json.dumps({'success': False, 'message': '参数错误，请检查客户端版本', 'code': 1}),
                        mimetype='application/json')
    quest = request.json
    try:
        try:
            phone = quest['phone']
        except:
            phone = ''
        try:
            email = quest['email']
        except:
            email = ''
        try:
            passwd = quest['password']
        except:
            passwd = ''

        if phone != '':
            if User_auth.query.filter_by(phone=phone).first():
                return Response(json.dumps({'success': False, 'message': '电话号码已被占用', 'code': 3}),
                                mimetype='application/json')
            current_user.phone = phone
        if email != '':
            if User_auth.query.filter_by(email=email).first():
                return Response(json.dumps({'success': False, 'message': '邮箱已被占用', 'code': 3}),
                                mimetype='application/json')
            current_user.email = email
        if passwd != '':
            if len(passwd) < 10:
                return Response(json.dumps({'success': False, 'message': '密码过短', 'code': 4}),
                                mimetype='application/json')
            current_user.set_password(passwd)

        db.session.commit()

        if passwd != '':
            flash("密码已修改，请重新登录", 'info')
            logout_user()
        else:
            flash("更新成功", "info")
        return Response(json.dumps({'success': True, 'message': '成功', 'code': 0}), mimetype='application/json')
    except BaseException as e:
        traceback.print_exc()
        print(e)
        return Response(json.dumps({'success': False, 'message': '服务器端发生错误', 'code': 1}), mimetype='application/json')

bishe/templates/_error.html
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://fonts.googleapis.com/css?family=Righteous&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/error.css') }}">
</head>
<body>
    <div class="moon"></div>
    <div class="moon__crater moon__crater1"></div>
    <div class="moon__crater moon__crater2"></div>
    <div class="moon__crater moon__crater3"></div>

    <div class="star star1"></div>
    <div class="star star2"></div>
    <div class="star star3"></div>
    <div class="star star4"></div>
    <div class="star star5"></div>

    <div class="error">
        <div class="error__title">{% block error_code %}{% endblock error_code %}</div>
        <div class="error__subtitle">Emmm...</div>
        <div class="error__subtitle">{% block description %}{% endblock description %}</div>
        <a href="{{ url_for('homepage.index') }}">
            <button class="error__button error__button--active" action="{{ url_for('homepage.index') }}">返回首页</button>
        </a>
    </div>

    <div class="astronaut">
        <div class="astronaut__backpack"></div>
        <div class="astronaut__body"></div>
        <div class="astronaut__body__chest"></div>
        <div class="astronaut__arm-left1"></div>
        <div class="astronaut__arm-left2"></div>
        <div class="astronaut__arm-right1"></div>
        <div class="astronaut__arm-right2"></div>
        <div class="astronaut__arm-thumb-left"></div>
        <div class="astronaut__arm-thumb-right"></div>
        <div class="astronaut__leg-left"></div>
        <div class="astronaut__leg-right"></div>
        <div class="astronaut__foot-left"></div>
        <div class="astronaut__foot-right"></div>
        <div class="astronaut__wrist-left"></div>
        <div class="astronaut__wrist-right"></div>

        <div class="astronaut__cord">
        <canvas id="cord" height="500px" width="500px"></canvas>
        </div>

        <div class="astronaut__head">
        <canvas id="visor" width="60px" height="60px"></canvas>
        <div class="astronaut__head-visor-flare1"></div>
        <div class="astronaut__head-visor-flare2"></div>
        </div>
    </div>

    <script  type="text/javascript" src="{{ url_for('static', filename='js/error.js') }}"></script>
</body>
</html>

bishe/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>{% block title %}{% endblock title %}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
        <link rel="stylesheet" href="{{ url_for('static', filename='fonts/ionicons.min.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
        {% block style %}{% endblock style %}
    {% endblock  head %}
</head>
<body>
{% block nav %}
    <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-white portfolio-navbar gradient">
        <div class="container">
            <a class="navbar-brand logo" href="{{ url_for('homepage.index') }}">学历查询认证系统</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" href="{{ url_for('users.cv') }}">个人中心</a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">退出</a>
                        </li>
                    {% else %}
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">注册</a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">登录</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock nav %}
{% block main %}{% endblock main %}
{% block footer %}
    <footer class="page-footer">
        <small> © 2020 <a class="blue-text link" href="#" title="Written by XiangYuan">XiangYuanLiu</a> -
            <a class="blue-text link" href="#" title="A HelloFlask project">山东大学计算机学院</a>
        </small>
    </footer>
{% endblock footer %}
{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.min.js') }}"></script>
{% endblock scripts %}
{% block js %}{% endblock js %}
</body>
</html>

bishe/templates/macros.html
{% macro form_field(field) %}
    {{ field.label }}
    {{ field(**kwargs) }}
    {% if field.errors %}
        {% for error in field.errors %}
            <div class="invalid-feedback d-block">{{ error }}</div>
        {% endfor %}
    {% endif %}
{% endmacro %}